services:
  api:
    container_name: tsb-api
    image: tsb_api
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
  sqlserver:
    container_name: tsb-sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234!
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver:/var/opt/mssql
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
