services:
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_USERNAME=sa
      - SA_PASSWORD=Password1234!
    ports:
      - 1433:1433
    expose:
      - "1433/UDP"

  # ///////////////////////////////////////////////

  api:
    build: .
    ports:
      - "80:80"
    expose:
      - "80/UDP"
    depends_on:
      - "database"
    
