name: Teste de Build .NET

# Controla quando esse workflow vai acontecer
on:
  # Ativa o workflow sempre que houver um push ou pull request mas apenas no branch 'main'
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Permite ativar este workflow na aba 'Actions'
  workflow_dispatch:

# Um workflow é composto de um ou mais jobs que podem rodar em sequência ou em paralelo
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps representam uma sequência de ações tomadas dentro de um job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install -g newman

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run
        run: dotnet run

      - name: Run tests
        run: newman run Tests/apicollection.json -e Tests/env.json -k --bail
