name: Build .NET

# Controla quando esse workflow vai acontecer
on:
  # Ativa o workflow sempre que houver um push ou pull request mas apenas no branch 'main'
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Permite ativar este workflow na aba 'Actions'
  workflow_dispatch:

# Um workflow é composto de um ou mais jobs que podem rodar em sequência ou em paralelo
jobs:
  build:
    runs-on: windows-latest

    # Steps representam uma sequência de ações tomadas dentro de um job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore
