name: Integration tests

on:
  push:
    branches: ["feature/**", "fix/**", "chore/**", "refactor/**"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SQL Server through Docker
        run: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password1234!" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Run test script
        run: sudo ./Source/Tests/Testing.bash
